// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Field data types enum.
 */
export enum DataType {
  Int8 = 0,
  Int16 = 1,
  Int32 = 2,
  Int64 = 3,
  Float32 = 4,
  Float64 = 5,
  Decimal = 6,
  Date = 7,
  Time = 8,
  Timestamp = 9,
  Binary = 10,
  Utf8 = 11
}
