// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Ordering types enum.
 */
export enum OrderType {
  None = 0,
  Asc = 1,
  Desc = 2
}
