// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Time type units enum.
 */
export enum TimeUnit {
  second = 0,
  millisecond = 1,
  microsecond = 2,
  nanosecond = 3
}
