// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Database connectors type.
type ConnectorTypesEnum int8

const (
	ConnectorTypesEnumPostgres      ConnectorTypesEnum = 0
	ConnectorTypesEnumMySQL         ConnectorTypesEnum = 1
	ConnectorTypesEnumMsSQL         ConnectorTypesEnum = 2
	ConnectorTypesEnumMariaDB       ConnectorTypesEnum = 3
	ConnectorTypesEnumOracle        ConnectorTypesEnum = 4
	ConnectorTypesEnumClickhouse    ConnectorTypesEnum = 5
	ConnectorTypesEnumDruid         ConnectorTypesEnum = 6
	ConnectorTypesEnumIgnite        ConnectorTypesEnum = 7
	ConnectorTypesEnumRedshift      ConnectorTypesEnum = 8
	ConnectorTypesEnumBigQuery      ConnectorTypesEnum = 9
	ConnectorTypesEnumGoogleSheets  ConnectorTypesEnum = 10
	ConnectorTypesEnumElasticSearch ConnectorTypesEnum = 11
	ConnectorTypesEnumMongoDB       ConnectorTypesEnum = 12
	ConnectorTypesEnumSnowflake     ConnectorTypesEnum = 13
)

var EnumNamesConnectorTypesEnum = map[ConnectorTypesEnum]string{
	ConnectorTypesEnumPostgres:      "Postgres",
	ConnectorTypesEnumMySQL:         "MySQL",
	ConnectorTypesEnumMsSQL:         "MsSQL",
	ConnectorTypesEnumMariaDB:       "MariaDB",
	ConnectorTypesEnumOracle:        "Oracle",
	ConnectorTypesEnumClickhouse:    "Clickhouse",
	ConnectorTypesEnumDruid:         "Druid",
	ConnectorTypesEnumIgnite:        "Ignite",
	ConnectorTypesEnumRedshift:      "Redshift",
	ConnectorTypesEnumBigQuery:      "BigQuery",
	ConnectorTypesEnumGoogleSheets:  "GoogleSheets",
	ConnectorTypesEnumElasticSearch: "ElasticSearch",
	ConnectorTypesEnumMongoDB:       "MongoDB",
	ConnectorTypesEnumSnowflake:     "Snowflake",
}

var EnumValuesConnectorTypesEnum = map[string]ConnectorTypesEnum{
	"Postgres":      ConnectorTypesEnumPostgres,
	"MySQL":         ConnectorTypesEnumMySQL,
	"MsSQL":         ConnectorTypesEnumMsSQL,
	"MariaDB":       ConnectorTypesEnumMariaDB,
	"Oracle":        ConnectorTypesEnumOracle,
	"Clickhouse":    ConnectorTypesEnumClickhouse,
	"Druid":         ConnectorTypesEnumDruid,
	"Ignite":        ConnectorTypesEnumIgnite,
	"Redshift":      ConnectorTypesEnumRedshift,
	"BigQuery":      ConnectorTypesEnumBigQuery,
	"GoogleSheets":  ConnectorTypesEnumGoogleSheets,
	"ElasticSearch": ConnectorTypesEnumElasticSearch,
	"MongoDB":       ConnectorTypesEnumMongoDB,
	"Snowflake":     ConnectorTypesEnumSnowflake,
}

func (v ConnectorTypesEnum) String() string {
	if s, ok := EnumNamesConnectorTypesEnum[v]; ok {
		return s
	}
	return "ConnectorTypesEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
