// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Date units enum.
type DateUnitEnum int8

const (
	DateUnitEnumSecond      DateUnitEnum = 0
	DateUnitEnumMillisecond DateUnitEnum = 1
)

var EnumNamesDateUnitEnum = map[DateUnitEnum]string{
	DateUnitEnumSecond:      "Second",
	DateUnitEnumMillisecond: "Millisecond",
}

var EnumValuesDateUnitEnum = map[string]DateUnitEnum{
	"Second":      DateUnitEnumSecond,
	"Millisecond": DateUnitEnumMillisecond,
}

func (v DateUnitEnum) String() string {
	if s, ok := EnumNamesDateUnitEnum[v]; ok {
		return s
	}
	return "DateUnitEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
