// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Query date units enum.
type DateUnit int8

const (
	DateUnitsecond      DateUnit = 0
	DateUnitmillisecond DateUnit = 1
)

var EnumNamesDateUnit = map[DateUnit]string{
	DateUnitsecond:      "second",
	DateUnitmillisecond: "millisecond",
}

var EnumValuesDateUnit = map[string]DateUnit{
	"second":      DateUnitsecond,
	"millisecond": DateUnitmillisecond,
}

func (v DateUnit) String() string {
	if s, ok := EnumNamesDateUnit[v]; ok {
		return s
	}
	return "DateUnit(" + strconv.FormatInt(int64(v), 10) + ")"
}
