// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Decimal data type bit width enum.
type DecBitWidth int8

const (
	DecBitWidth_128 DecBitWidth = 0
	DecBitWidth_256 DecBitWidth = 1
)

var EnumNamesDecBitWidth = map[DecBitWidth]string{
	DecBitWidth_128: "_128",
	DecBitWidth_256: "_256",
}

var EnumValuesDecBitWidth = map[string]DecBitWidth{
	"_128": DecBitWidth_128,
	"_256": DecBitWidth_256,
}

func (v DecBitWidth) String() string {
	if s, ok := EnumNamesDecBitWidth[v]; ok {
		return s
	}
	return "DecBitWidth(" + strconv.FormatInt(int64(v), 10) + ")"
}
