// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Deprecated. Delete it.
type FileState int8

const (
	FileStatePROCESSING FileState = 0
	FileStateSCHEMA     FileState = 1
	FileStateCHUNK      FileState = 2
	FileStateDONE       FileState = 3
	FileStateFAIL       FileState = 4
)

var EnumNamesFileState = map[FileState]string{
	FileStatePROCESSING: "PROCESSING",
	FileStateSCHEMA:     "SCHEMA",
	FileStateCHUNK:      "CHUNK",
	FileStateDONE:       "DONE",
	FileStateFAIL:       "FAIL",
}

var EnumValuesFileState = map[string]FileState{
	"PROCESSING": FileStatePROCESSING,
	"SCHEMA":     FileStateSCHEMA,
	"CHUNK":      FileStateCHUNK,
	"DONE":       FileStateDONE,
	"FAIL":       FileStateFAIL,
}

func (v FileState) String() string {
	if s, ok := EnumNamesFileState[v]; ok {
		return s
	}
	return "FileState(" + strconv.FormatInt(int64(v), 10) + ")"
}
