// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Query filter oprators enum.
type FilterOperator int8

const (
	FilterOperatorOr   FilterOperator = 0
	FilterOperatorAnd  FilterOperator = 1
	FilterOperatorNone FilterOperator = 2
)

var EnumNamesFilterOperator = map[FilterOperator]string{
	FilterOperatorOr:   "Or",
	FilterOperatorAnd:  "And",
	FilterOperatorNone: "None",
}

var EnumValuesFilterOperator = map[string]FilterOperator{
	"Or":   FilterOperatorOr,
	"And":  FilterOperatorAnd,
	"None": FilterOperatorNone,
}

func (v FilterOperator) String() string {
	if s, ok := EnumNamesFilterOperator[v]; ok {
		return s
	}
	return "FilterOperator(" + strconv.FormatInt(int64(v), 10) + ")"
}
