// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Filter oprators enum.
type FilterOperatorEnum int8

const (
	FilterOperatorEnumOr   FilterOperatorEnum = 0
	FilterOperatorEnumAnd  FilterOperatorEnum = 1
	FilterOperatorEnumNone FilterOperatorEnum = 2
)

var EnumNamesFilterOperatorEnum = map[FilterOperatorEnum]string{
	FilterOperatorEnumOr:   "Or",
	FilterOperatorEnumAnd:  "And",
	FilterOperatorEnumNone: "None",
}

var EnumValuesFilterOperatorEnum = map[string]FilterOperatorEnum{
	"Or":   FilterOperatorEnumOr,
	"And":  FilterOperatorEnumAnd,
	"None": FilterOperatorEnumNone,
}

func (v FilterOperatorEnum) String() string {
	if s, ok := EnumNamesFilterOperatorEnum[v]; ok {
		return s
	}
	return "FilterOperatorEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
