// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Filter names enum.
type FilterNameEnum int8

const (
	FilterNameEnumEquals       FilterNameEnum = 0
	FilterNameEnumNotEquals    FilterNameEnum = 1
	FilterNameEnumContains     FilterNameEnum = 2
	FilterNameEnumNotContains  FilterNameEnum = 3
	FilterNameEnumStartsWith   FilterNameEnum = 4
	FilterNameEnumEndsWith     FilterNameEnum = 5
	FilterNameEnumGreater      FilterNameEnum = 6
	FilterNameEnumGreaterEqual FilterNameEnum = 7
	FilterNameEnumLess         FilterNameEnum = 8
	FilterNameEnumLessEqual    FilterNameEnum = 9
	FilterNameEnumIsNull       FilterNameEnum = 10
	FilterNameEnumIsNotNull    FilterNameEnum = 11
	FilterNameEnumBetween      FilterNameEnum = 12
)

var EnumNamesFilterNameEnum = map[FilterNameEnum]string{
	FilterNameEnumEquals:       "Equals",
	FilterNameEnumNotEquals:    "NotEquals",
	FilterNameEnumContains:     "Contains",
	FilterNameEnumNotContains:  "NotContains",
	FilterNameEnumStartsWith:   "StartsWith",
	FilterNameEnumEndsWith:     "EndsWith",
	FilterNameEnumGreater:      "Greater",
	FilterNameEnumGreaterEqual: "GreaterEqual",
	FilterNameEnumLess:         "Less",
	FilterNameEnumLessEqual:    "LessEqual",
	FilterNameEnumIsNull:       "IsNull",
	FilterNameEnumIsNotNull:    "IsNotNull",
	FilterNameEnumBetween:      "Between",
}

var EnumValuesFilterNameEnum = map[string]FilterNameEnum{
	"Equals":       FilterNameEnumEquals,
	"NotEquals":    FilterNameEnumNotEquals,
	"Contains":     FilterNameEnumContains,
	"NotContains":  FilterNameEnumNotContains,
	"StartsWith":   FilterNameEnumStartsWith,
	"EndsWith":     FilterNameEnumEndsWith,
	"Greater":      FilterNameEnumGreater,
	"GreaterEqual": FilterNameEnumGreaterEqual,
	"Less":         FilterNameEnumLess,
	"LessEqual":    FilterNameEnumLessEqual,
	"IsNull":       FilterNameEnumIsNull,
	"IsNotNull":    FilterNameEnumIsNotNull,
	"Between":      FilterNameEnumBetween,
}

func (v FilterNameEnum) String() string {
	if s, ok := EnumNamesFilterNameEnum[v]; ok {
		return s
	}
	return "FilterNameEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
