// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Filter types enum.
type FilterTypeEnum int8

const (
	FilterTypeEnumExpression FilterTypeEnum = 0
	FilterTypeEnumKeys       FilterTypeEnum = 1
	FilterTypeEnumNamed      FilterTypeEnum = 2
)

var EnumNamesFilterTypeEnum = map[FilterTypeEnum]string{
	FilterTypeEnumExpression: "Expression",
	FilterTypeEnumKeys:       "Keys",
	FilterTypeEnumNamed:      "Named",
}

var EnumValuesFilterTypeEnum = map[string]FilterTypeEnum{
	"Expression": FilterTypeEnumExpression,
	"Keys":       FilterTypeEnumKeys,
	"Named":      FilterTypeEnumNamed,
}

func (v FilterTypeEnum) String() string {
	if s, ok := EnumNamesFilterTypeEnum[v]; ok {
		return s
	}
	return "FilterTypeEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
