// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Join types enum.
type JoinTypeEnum int8

const (
	JoinTypeEnumCross      JoinTypeEnum = 0
	JoinTypeEnumInner      JoinTypeEnum = 1
	JoinTypeEnumFull       JoinTypeEnum = 2
	JoinTypeEnumLeft       JoinTypeEnum = 3
	JoinTypeEnumRight      JoinTypeEnum = 4
	JoinTypeEnumFullOuter  JoinTypeEnum = 5
	JoinTypeEnumLeftOuter  JoinTypeEnum = 6
	JoinTypeEnumRightOuter JoinTypeEnum = 7
)

var EnumNamesJoinTypeEnum = map[JoinTypeEnum]string{
	JoinTypeEnumCross:      "Cross",
	JoinTypeEnumInner:      "Inner",
	JoinTypeEnumFull:       "Full",
	JoinTypeEnumLeft:       "Left",
	JoinTypeEnumRight:      "Right",
	JoinTypeEnumFullOuter:  "FullOuter",
	JoinTypeEnumLeftOuter:  "LeftOuter",
	JoinTypeEnumRightOuter: "RightOuter",
}

var EnumValuesJoinTypeEnum = map[string]JoinTypeEnum{
	"Cross":      JoinTypeEnumCross,
	"Inner":      JoinTypeEnumInner,
	"Full":       JoinTypeEnumFull,
	"Left":       JoinTypeEnumLeft,
	"Right":      JoinTypeEnumRight,
	"FullOuter":  JoinTypeEnumFullOuter,
	"LeftOuter":  JoinTypeEnumLeftOuter,
	"RightOuter": JoinTypeEnumRightOuter,
}

func (v JoinTypeEnum) String() string {
	if s, ok := EnumNamesJoinTypeEnum[v]; ok {
		return s
	}
	return "JoinTypeEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
