// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Ordering types enum.
type OrderTypeEnum int8

const (
	OrderTypeEnumNone       OrderTypeEnum = 0
	OrderTypeEnumAscending  OrderTypeEnum = 1
	OrderTypeEnumDescending OrderTypeEnum = 2
)

var EnumNamesOrderTypeEnum = map[OrderTypeEnum]string{
	OrderTypeEnumNone:       "None",
	OrderTypeEnumAscending:  "Ascending",
	OrderTypeEnumDescending: "Descending",
}

var EnumValuesOrderTypeEnum = map[string]OrderTypeEnum{
	"None":       OrderTypeEnumNone,
	"Ascending":  OrderTypeEnumAscending,
	"Descending": OrderTypeEnumDescending,
}

func (v OrderTypeEnum) String() string {
	if s, ok := EnumNamesOrderTypeEnum[v]; ok {
		return s
	}
	return "OrderTypeEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
