// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Posted query state enum.
type QueryState int8

const (
	QueryStatePROCESSING QueryState = 0
	QueryStateSCHEMA     QueryState = 1
	QueryStateCHUNK      QueryState = 2
	QueryStateDONE       QueryState = 3
	QueryStateFAIL       QueryState = 4
)

var EnumNamesQueryState = map[QueryState]string{
	QueryStatePROCESSING: "PROCESSING",
	QueryStateSCHEMA:     "SCHEMA",
	QueryStateCHUNK:      "CHUNK",
	QueryStateDONE:       "DONE",
	QueryStateFAIL:       "FAIL",
}

var EnumValuesQueryState = map[string]QueryState{
	"PROCESSING": QueryStatePROCESSING,
	"SCHEMA":     QueryStateSCHEMA,
	"CHUNK":      QueryStateCHUNK,
	"DONE":       QueryStateDONE,
	"FAIL":       QueryStateFAIL,
}

func (v QueryState) String() string {
	if s, ok := EnumNamesQueryState[v]; ok {
		return s
	}
	return "QueryState(" + strconv.FormatInt(int64(v), 10) + ")"
}
