// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Query table types enum.
type TableType int8

const (
	TableTypeJson  TableType = 0
	TableTypeCsv   TableType = 1
	TableTypeTable TableType = 2
	TableTypeQuery TableType = 3
)

var EnumNamesTableType = map[TableType]string{
	TableTypeJson:  "Json",
	TableTypeCsv:   "Csv",
	TableTypeTable: "Table",
	TableTypeQuery: "Query",
}

var EnumValuesTableType = map[string]TableType{
	"Json":  TableTypeJson,
	"Csv":   TableTypeCsv,
	"Table": TableTypeTable,
	"Query": TableTypeQuery,
}

func (v TableType) String() string {
	if s, ok := EnumNamesTableType[v]; ok {
		return s
	}
	return "TableType(" + strconv.FormatInt(int64(v), 10) + ")"
}
