// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Table types enum.
type TableTypeEnum int8

const (
	TableTypeEnumTable TableTypeEnum = 0
	TableTypeEnumQuery TableTypeEnum = 1
)

var EnumNamesTableTypeEnum = map[TableTypeEnum]string{
	TableTypeEnumTable: "Table",
	TableTypeEnumQuery: "Query",
}

var EnumValuesTableTypeEnum = map[string]TableTypeEnum{
	"Table": TableTypeEnumTable,
	"Query": TableTypeEnumQuery,
}

func (v TableTypeEnum) String() string {
	if s, ok := EnumNamesTableTypeEnum[v]; ok {
		return s
	}
	return "TableTypeEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
