// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Time units enum.
type TimeUnitEnum int8

const (
	TimeUnitEnumSecond      TimeUnitEnum = 0
	TimeUnitEnumMillisecond TimeUnitEnum = 1
	TimeUnitEnumMicrosecond TimeUnitEnum = 2
	TimeUnitEnumNanosecond  TimeUnitEnum = 3
)

var EnumNamesTimeUnitEnum = map[TimeUnitEnum]string{
	TimeUnitEnumSecond:      "Second",
	TimeUnitEnumMillisecond: "Millisecond",
	TimeUnitEnumMicrosecond: "Microsecond",
	TimeUnitEnumNanosecond:  "Nanosecond",
}

var EnumValuesTimeUnitEnum = map[string]TimeUnitEnum{
	"Second":      TimeUnitEnumSecond,
	"Millisecond": TimeUnitEnumMillisecond,
	"Microsecond": TimeUnitEnumMicrosecond,
	"Nanosecond":  TimeUnitEnumNanosecond,
}

func (v TimeUnitEnum) String() string {
	if s, ok := EnumNamesTimeUnitEnum[v]; ok {
		return s
	}
	return "TimeUnitEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
