// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Query time zone enum.
type TimeZone int16

const (
	TimeZoneGMT_00 TimeZone = 0
	TimeZoneGMT_01 TimeZone = 1
	TimeZoneGMT_02 TimeZone = 2
	TimeZoneGMT_03 TimeZone = 3
	TimeZoneGMT_04 TimeZone = 4
	TimeZoneGMT_05 TimeZone = 5
	TimeZoneGMT_06 TimeZone = 6
	TimeZoneGMT_07 TimeZone = 7
	TimeZoneGMT_08 TimeZone = 8
	TimeZoneGMT_09 TimeZone = 9
	TimeZoneGMT_10 TimeZone = 10
	TimeZoneGMT_11 TimeZone = 11
	TimeZoneGMT_12 TimeZone = 12
	TimeZoneGMT_13 TimeZone = 13
	TimeZoneGMT_14 TimeZone = 14
	TimeZoneGMT_15 TimeZone = 15
	TimeZoneGMT_16 TimeZone = 16
	TimeZoneGMT_17 TimeZone = 17
	TimeZoneGMT_18 TimeZone = 18
	TimeZoneGMT_19 TimeZone = 19
	TimeZoneGMT_20 TimeZone = 20
	TimeZoneGMT_21 TimeZone = 21
	TimeZoneGMT_22 TimeZone = 22
	TimeZoneGMT_23 TimeZone = 23
	TimeZoneUTC_00 TimeZone = 24
	TimeZoneUTC_01 TimeZone = 25
	TimeZoneUTC_02 TimeZone = 26
	TimeZoneUTC_03 TimeZone = 27
	TimeZoneUTC_04 TimeZone = 28
	TimeZoneUTC_05 TimeZone = 29
	TimeZoneUTC_06 TimeZone = 30
	TimeZoneUTC_07 TimeZone = 31
	TimeZoneUTC_08 TimeZone = 32
	TimeZoneUTC_09 TimeZone = 33
	TimeZoneUTC_10 TimeZone = 34
	TimeZoneUTC_11 TimeZone = 35
	TimeZoneUTC_12 TimeZone = 36
	TimeZoneUTC_13 TimeZone = 37
	TimeZoneUTC_14 TimeZone = 38
	TimeZoneUTC_15 TimeZone = 39
	TimeZoneUTC_16 TimeZone = 40
	TimeZoneUTC_17 TimeZone = 41
	TimeZoneUTC_18 TimeZone = 42
	TimeZoneUTC_19 TimeZone = 43
	TimeZoneUTC_20 TimeZone = 44
	TimeZoneUTC_21 TimeZone = 45
	TimeZoneUTC_22 TimeZone = 46
	TimeZoneUTC_23 TimeZone = 47
)

var EnumNamesTimeZone = map[TimeZone]string{
	TimeZoneGMT_00: "GMT_00",
	TimeZoneGMT_01: "GMT_01",
	TimeZoneGMT_02: "GMT_02",
	TimeZoneGMT_03: "GMT_03",
	TimeZoneGMT_04: "GMT_04",
	TimeZoneGMT_05: "GMT_05",
	TimeZoneGMT_06: "GMT_06",
	TimeZoneGMT_07: "GMT_07",
	TimeZoneGMT_08: "GMT_08",
	TimeZoneGMT_09: "GMT_09",
	TimeZoneGMT_10: "GMT_10",
	TimeZoneGMT_11: "GMT_11",
	TimeZoneGMT_12: "GMT_12",
	TimeZoneGMT_13: "GMT_13",
	TimeZoneGMT_14: "GMT_14",
	TimeZoneGMT_15: "GMT_15",
	TimeZoneGMT_16: "GMT_16",
	TimeZoneGMT_17: "GMT_17",
	TimeZoneGMT_18: "GMT_18",
	TimeZoneGMT_19: "GMT_19",
	TimeZoneGMT_20: "GMT_20",
	TimeZoneGMT_21: "GMT_21",
	TimeZoneGMT_22: "GMT_22",
	TimeZoneGMT_23: "GMT_23",
	TimeZoneUTC_00: "UTC_00",
	TimeZoneUTC_01: "UTC_01",
	TimeZoneUTC_02: "UTC_02",
	TimeZoneUTC_03: "UTC_03",
	TimeZoneUTC_04: "UTC_04",
	TimeZoneUTC_05: "UTC_05",
	TimeZoneUTC_06: "UTC_06",
	TimeZoneUTC_07: "UTC_07",
	TimeZoneUTC_08: "UTC_08",
	TimeZoneUTC_09: "UTC_09",
	TimeZoneUTC_10: "UTC_10",
	TimeZoneUTC_11: "UTC_11",
	TimeZoneUTC_12: "UTC_12",
	TimeZoneUTC_13: "UTC_13",
	TimeZoneUTC_14: "UTC_14",
	TimeZoneUTC_15: "UTC_15",
	TimeZoneUTC_16: "UTC_16",
	TimeZoneUTC_17: "UTC_17",
	TimeZoneUTC_18: "UTC_18",
	TimeZoneUTC_19: "UTC_19",
	TimeZoneUTC_20: "UTC_20",
	TimeZoneUTC_21: "UTC_21",
	TimeZoneUTC_22: "UTC_22",
	TimeZoneUTC_23: "UTC_23",
}

var EnumValuesTimeZone = map[string]TimeZone{
	"GMT_00": TimeZoneGMT_00,
	"GMT_01": TimeZoneGMT_01,
	"GMT_02": TimeZoneGMT_02,
	"GMT_03": TimeZoneGMT_03,
	"GMT_04": TimeZoneGMT_04,
	"GMT_05": TimeZoneGMT_05,
	"GMT_06": TimeZoneGMT_06,
	"GMT_07": TimeZoneGMT_07,
	"GMT_08": TimeZoneGMT_08,
	"GMT_09": TimeZoneGMT_09,
	"GMT_10": TimeZoneGMT_10,
	"GMT_11": TimeZoneGMT_11,
	"GMT_12": TimeZoneGMT_12,
	"GMT_13": TimeZoneGMT_13,
	"GMT_14": TimeZoneGMT_14,
	"GMT_15": TimeZoneGMT_15,
	"GMT_16": TimeZoneGMT_16,
	"GMT_17": TimeZoneGMT_17,
	"GMT_18": TimeZoneGMT_18,
	"GMT_19": TimeZoneGMT_19,
	"GMT_20": TimeZoneGMT_20,
	"GMT_21": TimeZoneGMT_21,
	"GMT_22": TimeZoneGMT_22,
	"GMT_23": TimeZoneGMT_23,
	"UTC_00": TimeZoneUTC_00,
	"UTC_01": TimeZoneUTC_01,
	"UTC_02": TimeZoneUTC_02,
	"UTC_03": TimeZoneUTC_03,
	"UTC_04": TimeZoneUTC_04,
	"UTC_05": TimeZoneUTC_05,
	"UTC_06": TimeZoneUTC_06,
	"UTC_07": TimeZoneUTC_07,
	"UTC_08": TimeZoneUTC_08,
	"UTC_09": TimeZoneUTC_09,
	"UTC_10": TimeZoneUTC_10,
	"UTC_11": TimeZoneUTC_11,
	"UTC_12": TimeZoneUTC_12,
	"UTC_13": TimeZoneUTC_13,
	"UTC_14": TimeZoneUTC_14,
	"UTC_15": TimeZoneUTC_15,
	"UTC_16": TimeZoneUTC_16,
	"UTC_17": TimeZoneUTC_17,
	"UTC_18": TimeZoneUTC_18,
	"UTC_19": TimeZoneUTC_19,
	"UTC_20": TimeZoneUTC_20,
	"UTC_21": TimeZoneUTC_21,
	"UTC_22": TimeZoneUTC_22,
	"UTC_23": TimeZoneUTC_23,
}

func (v TimeZone) String() string {
	if s, ok := EnumNamesTimeZone[v]; ok {
		return s
	}
	return "TimeZone(" + strconv.FormatInt(int64(v), 10) + ")"
}
