// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Supported Timezones enum.
type TimeZoneEnum int16

const (
	TimeZoneEnumUTC      TimeZoneEnum = 0
	TimeZoneEnumGMT      TimeZoneEnum = 1
	TimeZoneEnumGMT_m_12 TimeZoneEnum = 2
	TimeZoneEnumGMT_m_11 TimeZoneEnum = 3
	TimeZoneEnumGMT_m_10 TimeZoneEnum = 4
	TimeZoneEnumGMT_m_09 TimeZoneEnum = 5
	TimeZoneEnumGMT_m_08 TimeZoneEnum = 6
	TimeZoneEnumGMT_m_07 TimeZoneEnum = 7
	TimeZoneEnumGMT_m_06 TimeZoneEnum = 8
	TimeZoneEnumGMT_m_05 TimeZoneEnum = 9
	TimeZoneEnumGMT_m_04 TimeZoneEnum = 10
	TimeZoneEnumGMT_m_03 TimeZoneEnum = 11
	TimeZoneEnumGMT_m_02 TimeZoneEnum = 12
	TimeZoneEnumGMT_m_01 TimeZoneEnum = 13
	TimeZoneEnumGMT_p_01 TimeZoneEnum = 14
	TimeZoneEnumGMT_p_02 TimeZoneEnum = 15
	TimeZoneEnumGMT_p_03 TimeZoneEnum = 16
	TimeZoneEnumGMT_p_04 TimeZoneEnum = 17
	TimeZoneEnumGMT_p_05 TimeZoneEnum = 18
	TimeZoneEnumGMT_p_06 TimeZoneEnum = 19
	TimeZoneEnumGMT_p_07 TimeZoneEnum = 20
	TimeZoneEnumGMT_p_08 TimeZoneEnum = 21
	TimeZoneEnumGMT_p_09 TimeZoneEnum = 22
	TimeZoneEnumGMT_p_10 TimeZoneEnum = 23
	TimeZoneEnumGMT_p_11 TimeZoneEnum = 24
	TimeZoneEnumGMT_p_12 TimeZoneEnum = 25
	TimeZoneEnumGMT_p_13 TimeZoneEnum = 26
	TimeZoneEnumGMT_p_14 TimeZoneEnum = 27
)

var EnumNamesTimeZoneEnum = map[TimeZoneEnum]string{
	TimeZoneEnumUTC:      "UTC",
	TimeZoneEnumGMT:      "GMT",
	TimeZoneEnumGMT_m_12: "GMT_m_12",
	TimeZoneEnumGMT_m_11: "GMT_m_11",
	TimeZoneEnumGMT_m_10: "GMT_m_10",
	TimeZoneEnumGMT_m_09: "GMT_m_09",
	TimeZoneEnumGMT_m_08: "GMT_m_08",
	TimeZoneEnumGMT_m_07: "GMT_m_07",
	TimeZoneEnumGMT_m_06: "GMT_m_06",
	TimeZoneEnumGMT_m_05: "GMT_m_05",
	TimeZoneEnumGMT_m_04: "GMT_m_04",
	TimeZoneEnumGMT_m_03: "GMT_m_03",
	TimeZoneEnumGMT_m_02: "GMT_m_02",
	TimeZoneEnumGMT_m_01: "GMT_m_01",
	TimeZoneEnumGMT_p_01: "GMT_p_01",
	TimeZoneEnumGMT_p_02: "GMT_p_02",
	TimeZoneEnumGMT_p_03: "GMT_p_03",
	TimeZoneEnumGMT_p_04: "GMT_p_04",
	TimeZoneEnumGMT_p_05: "GMT_p_05",
	TimeZoneEnumGMT_p_06: "GMT_p_06",
	TimeZoneEnumGMT_p_07: "GMT_p_07",
	TimeZoneEnumGMT_p_08: "GMT_p_08",
	TimeZoneEnumGMT_p_09: "GMT_p_09",
	TimeZoneEnumGMT_p_10: "GMT_p_10",
	TimeZoneEnumGMT_p_11: "GMT_p_11",
	TimeZoneEnumGMT_p_12: "GMT_p_12",
	TimeZoneEnumGMT_p_13: "GMT_p_13",
	TimeZoneEnumGMT_p_14: "GMT_p_14",
}

var EnumValuesTimeZoneEnum = map[string]TimeZoneEnum{
	"UTC":      TimeZoneEnumUTC,
	"GMT":      TimeZoneEnumGMT,
	"GMT_m_12": TimeZoneEnumGMT_m_12,
	"GMT_m_11": TimeZoneEnumGMT_m_11,
	"GMT_m_10": TimeZoneEnumGMT_m_10,
	"GMT_m_09": TimeZoneEnumGMT_m_09,
	"GMT_m_08": TimeZoneEnumGMT_m_08,
	"GMT_m_07": TimeZoneEnumGMT_m_07,
	"GMT_m_06": TimeZoneEnumGMT_m_06,
	"GMT_m_05": TimeZoneEnumGMT_m_05,
	"GMT_m_04": TimeZoneEnumGMT_m_04,
	"GMT_m_03": TimeZoneEnumGMT_m_03,
	"GMT_m_02": TimeZoneEnumGMT_m_02,
	"GMT_m_01": TimeZoneEnumGMT_m_01,
	"GMT_p_01": TimeZoneEnumGMT_p_01,
	"GMT_p_02": TimeZoneEnumGMT_p_02,
	"GMT_p_03": TimeZoneEnumGMT_p_03,
	"GMT_p_04": TimeZoneEnumGMT_p_04,
	"GMT_p_05": TimeZoneEnumGMT_p_05,
	"GMT_p_06": TimeZoneEnumGMT_p_06,
	"GMT_p_07": TimeZoneEnumGMT_p_07,
	"GMT_p_08": TimeZoneEnumGMT_p_08,
	"GMT_p_09": TimeZoneEnumGMT_p_09,
	"GMT_p_10": TimeZoneEnumGMT_p_10,
	"GMT_p_11": TimeZoneEnumGMT_p_11,
	"GMT_p_12": TimeZoneEnumGMT_p_12,
	"GMT_p_13": TimeZoneEnumGMT_p_13,
	"GMT_p_14": TimeZoneEnumGMT_p_14,
}

func (v TimeZoneEnum) String() string {
	if s, ok := EnumNamesTimeZoneEnum[v]; ok {
		return s
	}
	return "TimeZoneEnum(" + strconv.FormatInt(int64(v), 10) + ")"
}
