// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Query time unit enum.
type TimeUnit int8

const (
	TimeUnitsecond      TimeUnit = 0
	TimeUnitmillisecond TimeUnit = 1
	TimeUnitmicrosecond TimeUnit = 2
	TimeUnitnanosecond  TimeUnit = 3
)

var EnumNamesTimeUnit = map[TimeUnit]string{
	TimeUnitsecond:      "second",
	TimeUnitmillisecond: "millisecond",
	TimeUnitmicrosecond: "microsecond",
	TimeUnitnanosecond:  "nanosecond",
}

var EnumValuesTimeUnit = map[string]TimeUnit{
	"second":      TimeUnitsecond,
	"millisecond": TimeUnitmillisecond,
	"microsecond": TimeUnitmicrosecond,
	"nanosecond":  TimeUnitnanosecond,
}

func (v TimeUnit) String() string {
	if s, ok := EnumNamesTimeUnit[v]; ok {
		return s
	}
	return "TimeUnit(" + strconv.FormatInt(int64(v), 10) + ")"
}
