// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Supported Timezones enum.
type TimeZone int16

const (
	TimeZoneUTC      TimeZone = 0
	TimeZoneGMT      TimeZone = 1
	TimeZoneGMT_m_12 TimeZone = 2
	TimeZoneGMT_m_11 TimeZone = 3
	TimeZoneGMT_m_10 TimeZone = 4
	TimeZoneGMT_m_09 TimeZone = 5
	TimeZoneGMT_m_08 TimeZone = 6
	TimeZoneGMT_m_07 TimeZone = 7
	TimeZoneGMT_m_06 TimeZone = 8
	TimeZoneGMT_m_05 TimeZone = 9
	TimeZoneGMT_m_04 TimeZone = 10
	TimeZoneGMT_m_03 TimeZone = 11
	TimeZoneGMT_m_02 TimeZone = 12
	TimeZoneGMT_m_01 TimeZone = 13
	TimeZoneGMT_p_01 TimeZone = 14
	TimeZoneGMT_p_02 TimeZone = 15
	TimeZoneGMT_p_03 TimeZone = 16
	TimeZoneGMT_p_04 TimeZone = 17
	TimeZoneGMT_p_05 TimeZone = 18
	TimeZoneGMT_p_06 TimeZone = 19
	TimeZoneGMT_p_07 TimeZone = 20
	TimeZoneGMT_p_08 TimeZone = 21
	TimeZoneGMT_p_09 TimeZone = 22
	TimeZoneGMT_p_10 TimeZone = 23
	TimeZoneGMT_p_11 TimeZone = 24
	TimeZoneGMT_p_12 TimeZone = 25
	TimeZoneGMT_p_13 TimeZone = 26
	TimeZoneGMT_p_14 TimeZone = 27
)

var EnumNamesTimeZone = map[TimeZone]string{
	TimeZoneUTC:      "UTC",
	TimeZoneGMT:      "GMT",
	TimeZoneGMT_m_12: "GMT_m_12",
	TimeZoneGMT_m_11: "GMT_m_11",
	TimeZoneGMT_m_10: "GMT_m_10",
	TimeZoneGMT_m_09: "GMT_m_09",
	TimeZoneGMT_m_08: "GMT_m_08",
	TimeZoneGMT_m_07: "GMT_m_07",
	TimeZoneGMT_m_06: "GMT_m_06",
	TimeZoneGMT_m_05: "GMT_m_05",
	TimeZoneGMT_m_04: "GMT_m_04",
	TimeZoneGMT_m_03: "GMT_m_03",
	TimeZoneGMT_m_02: "GMT_m_02",
	TimeZoneGMT_m_01: "GMT_m_01",
	TimeZoneGMT_p_01: "GMT_p_01",
	TimeZoneGMT_p_02: "GMT_p_02",
	TimeZoneGMT_p_03: "GMT_p_03",
	TimeZoneGMT_p_04: "GMT_p_04",
	TimeZoneGMT_p_05: "GMT_p_05",
	TimeZoneGMT_p_06: "GMT_p_06",
	TimeZoneGMT_p_07: "GMT_p_07",
	TimeZoneGMT_p_08: "GMT_p_08",
	TimeZoneGMT_p_09: "GMT_p_09",
	TimeZoneGMT_p_10: "GMT_p_10",
	TimeZoneGMT_p_11: "GMT_p_11",
	TimeZoneGMT_p_12: "GMT_p_12",
	TimeZoneGMT_p_13: "GMT_p_13",
	TimeZoneGMT_p_14: "GMT_p_14",
}

var EnumValuesTimeZone = map[string]TimeZone{
	"UTC":      TimeZoneUTC,
	"GMT":      TimeZoneGMT,
	"GMT_m_12": TimeZoneGMT_m_12,
	"GMT_m_11": TimeZoneGMT_m_11,
	"GMT_m_10": TimeZoneGMT_m_10,
	"GMT_m_09": TimeZoneGMT_m_09,
	"GMT_m_08": TimeZoneGMT_m_08,
	"GMT_m_07": TimeZoneGMT_m_07,
	"GMT_m_06": TimeZoneGMT_m_06,
	"GMT_m_05": TimeZoneGMT_m_05,
	"GMT_m_04": TimeZoneGMT_m_04,
	"GMT_m_03": TimeZoneGMT_m_03,
	"GMT_m_02": TimeZoneGMT_m_02,
	"GMT_m_01": TimeZoneGMT_m_01,
	"GMT_p_01": TimeZoneGMT_p_01,
	"GMT_p_02": TimeZoneGMT_p_02,
	"GMT_p_03": TimeZoneGMT_p_03,
	"GMT_p_04": TimeZoneGMT_p_04,
	"GMT_p_05": TimeZoneGMT_p_05,
	"GMT_p_06": TimeZoneGMT_p_06,
	"GMT_p_07": TimeZoneGMT_p_07,
	"GMT_p_08": TimeZoneGMT_p_08,
	"GMT_p_09": TimeZoneGMT_p_09,
	"GMT_p_10": TimeZoneGMT_p_10,
	"GMT_p_11": TimeZoneGMT_p_11,
	"GMT_p_12": TimeZoneGMT_p_12,
	"GMT_p_13": TimeZoneGMT_p_13,
	"GMT_p_14": TimeZoneGMT_p_14,
}

func (v TimeZone) String() string {
	if s, ok := EnumNamesTimeZone[v]; ok {
		return s
	}
	return "TimeZone(" + strconv.FormatInt(int64(v), 10) + ")"
}
