// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Options to connect to the BigQuery.
type BigQueryOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsBigQueryOptions(buf []byte, offset flatbuffers.UOffsetT) *BigQueryOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BigQueryOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishBigQueryOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBigQueryOptions(buf []byte, offset flatbuffers.UOffsetT) *BigQueryOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BigQueryOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBigQueryOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BigQueryOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BigQueryOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BigQueryOptions) ProjectId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BigQueryOptions) CredentialsKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BigQueryOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BigQueryOptionsAddProjectId(builder *flatbuffers.Builder, projectId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(projectId), 0)
}
func BigQueryOptionsAddCredentialsKey(builder *flatbuffers.Builder, credentialsKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(credentialsKey), 0)
}
func BigQueryOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
