// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Common data type parameters structure.
type CommonParametersStruct struct {
	_tab flatbuffers.Table
}

func GetRootAsCommonParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *CommonParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommonParametersStruct{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommonParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommonParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *CommonParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommonParametersStruct{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommonParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CommonParametersStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommonParametersStruct) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommonParametersStruct) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CommonParametersStruct) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func CommonParametersStructStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CommonParametersStructAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func CommonParametersStructEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
