// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Union type to describe DB connection options.
type ConnectionOptionsUnion byte

const (
	ConnectionOptionsUnionNONE                 ConnectionOptionsUnion = 0
	ConnectionOptionsUnionJDBCOptions          ConnectionOptionsUnion = 1
	ConnectionOptionsUnionBigQueryOptions      ConnectionOptionsUnion = 2
	ConnectionOptionsUnionGoogleSheetsOptions  ConnectionOptionsUnion = 3
	ConnectionOptionsUnionElasticsearchOptions ConnectionOptionsUnion = 4
	ConnectionOptionsUnionMongoDBOptions       ConnectionOptionsUnion = 5
)

var EnumNamesConnectionOptionsUnion = map[ConnectionOptionsUnion]string{
	ConnectionOptionsUnionNONE:                 "NONE",
	ConnectionOptionsUnionJDBCOptions:          "JDBCOptions",
	ConnectionOptionsUnionBigQueryOptions:      "BigQueryOptions",
	ConnectionOptionsUnionGoogleSheetsOptions:  "GoogleSheetsOptions",
	ConnectionOptionsUnionElasticsearchOptions: "ElasticsearchOptions",
	ConnectionOptionsUnionMongoDBOptions:       "MongoDBOptions",
}

var EnumValuesConnectionOptionsUnion = map[string]ConnectionOptionsUnion{
	"NONE":                 ConnectionOptionsUnionNONE,
	"JDBCOptions":          ConnectionOptionsUnionJDBCOptions,
	"BigQueryOptions":      ConnectionOptionsUnionBigQueryOptions,
	"GoogleSheetsOptions":  ConnectionOptionsUnionGoogleSheetsOptions,
	"ElasticsearchOptions": ConnectionOptionsUnionElasticsearchOptions,
	"MongoDBOptions":       ConnectionOptionsUnionMongoDBOptions,
}

func (v ConnectionOptionsUnion) String() string {
	if s, ok := EnumNamesConnectionOptionsUnion[v]; ok {
		return s
	}
	return "ConnectionOptionsUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
