// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Union type to describe DB connection parameters.
type ConnectionParametersStruct byte

const (
	ConnectionParametersStructNONE                          ConnectionParametersStruct = 0
	ConnectionParametersStructJDBCParametersStruct          ConnectionParametersStruct = 1
	ConnectionParametersStructBigQueryParametersStruct      ConnectionParametersStruct = 2
	ConnectionParametersStructGoogleSheetsParametersStruct  ConnectionParametersStruct = 3
	ConnectionParametersStructElasticsearchParametersStruct ConnectionParametersStruct = 4
	ConnectionParametersStructMongoDBParametersStruct       ConnectionParametersStruct = 5
	ConnectionParametersStructSnowflakeParametersStruct     ConnectionParametersStruct = 6
)

var EnumNamesConnectionParametersStruct = map[ConnectionParametersStruct]string{
	ConnectionParametersStructNONE:                          "NONE",
	ConnectionParametersStructJDBCParametersStruct:          "JDBCParametersStruct",
	ConnectionParametersStructBigQueryParametersStruct:      "BigQueryParametersStruct",
	ConnectionParametersStructGoogleSheetsParametersStruct:  "GoogleSheetsParametersStruct",
	ConnectionParametersStructElasticsearchParametersStruct: "ElasticsearchParametersStruct",
	ConnectionParametersStructMongoDBParametersStruct:       "MongoDBParametersStruct",
	ConnectionParametersStructSnowflakeParametersStruct:     "SnowflakeParametersStruct",
}

var EnumValuesConnectionParametersStruct = map[string]ConnectionParametersStruct{
	"NONE":                          ConnectionParametersStructNONE,
	"JDBCParametersStruct":          ConnectionParametersStructJDBCParametersStruct,
	"BigQueryParametersStruct":      ConnectionParametersStructBigQueryParametersStruct,
	"GoogleSheetsParametersStruct":  ConnectionParametersStructGoogleSheetsParametersStruct,
	"ElasticsearchParametersStruct": ConnectionParametersStructElasticsearchParametersStruct,
	"MongoDBParametersStruct":       ConnectionParametersStructMongoDBParametersStruct,
	"SnowflakeParametersStruct":     ConnectionParametersStructSnowflakeParametersStruct,
}

func (v ConnectionParametersStruct) String() string {
	if s, ok := EnumNamesConnectionParametersStruct[v]; ok {
		return s
	}
	return "ConnectionParametersStruct(" + strconv.FormatInt(int64(v), 10) + ")"
}
