// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Data type options.
type DataTypeOptions byte

const (
	DataTypeOptionsNONE                DataTypeOptions = 0
	DataTypeOptionsCommonParameters    DataTypeOptions = 1
	DataTypeOptionsDecimalParameters   DataTypeOptions = 2
	DataTypeOptionsDateParameters      DataTypeOptions = 3
	DataTypeOptionsTimeParameters      DataTypeOptions = 4
	DataTypeOptionsTimestampParameters DataTypeOptions = 5
)

var EnumNamesDataTypeOptions = map[DataTypeOptions]string{
	DataTypeOptionsNONE:                "NONE",
	DataTypeOptionsCommonParameters:    "CommonParameters",
	DataTypeOptionsDecimalParameters:   "DecimalParameters",
	DataTypeOptionsDateParameters:      "DateParameters",
	DataTypeOptionsTimeParameters:      "TimeParameters",
	DataTypeOptionsTimestampParameters: "TimestampParameters",
}

var EnumValuesDataTypeOptions = map[string]DataTypeOptions{
	"NONE":                DataTypeOptionsNONE,
	"CommonParameters":    DataTypeOptionsCommonParameters,
	"DecimalParameters":   DataTypeOptionsDecimalParameters,
	"DateParameters":      DataTypeOptionsDateParameters,
	"TimeParameters":      DataTypeOptionsTimeParameters,
	"TimestampParameters": DataTypeOptionsTimestampParameters,
}

func (v DataTypeOptions) String() string {
	if s, ok := EnumNamesDataTypeOptions[v]; ok {
		return s
	}
	return "DataTypeOptions(" + strconv.FormatInt(int64(v), 10) + ")"
}
