// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Data type options.
type DataTypeOptionsStruct byte

const (
	DataTypeOptionsStructNONE                      DataTypeOptionsStruct = 0
	DataTypeOptionsStructCommonParametersStruct    DataTypeOptionsStruct = 1
	DataTypeOptionsStructDecimalParametersStruct   DataTypeOptionsStruct = 2
	DataTypeOptionsStructDateParametersStruct      DataTypeOptionsStruct = 3
	DataTypeOptionsStructTimeParametersStruct      DataTypeOptionsStruct = 4
	DataTypeOptionsStructTimestampParametersStruct DataTypeOptionsStruct = 5
)

var EnumNamesDataTypeOptionsStruct = map[DataTypeOptionsStruct]string{
	DataTypeOptionsStructNONE:                      "NONE",
	DataTypeOptionsStructCommonParametersStruct:    "CommonParametersStruct",
	DataTypeOptionsStructDecimalParametersStruct:   "DecimalParametersStruct",
	DataTypeOptionsStructDateParametersStruct:      "DateParametersStruct",
	DataTypeOptionsStructTimeParametersStruct:      "TimeParametersStruct",
	DataTypeOptionsStructTimestampParametersStruct: "TimestampParametersStruct",
}

var EnumValuesDataTypeOptionsStruct = map[string]DataTypeOptionsStruct{
	"NONE":                      DataTypeOptionsStructNONE,
	"CommonParametersStruct":    DataTypeOptionsStructCommonParametersStruct,
	"DecimalParametersStruct":   DataTypeOptionsStructDecimalParametersStruct,
	"DateParametersStruct":      DataTypeOptionsStructDateParametersStruct,
	"TimeParametersStruct":      DataTypeOptionsStructTimeParametersStruct,
	"TimestampParametersStruct": DataTypeOptionsStructTimestampParametersStruct,
}

func (v DataTypeOptionsStruct) String() string {
	if s, ok := EnumNamesDataTypeOptionsStruct[v]; ok {
		return s
	}
	return "DataTypeOptionsStruct(" + strconv.FormatInt(int64(v), 10) + ")"
}
