// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Data type options.
type DataTypeOptionsStruct byte

const (
	DataTypeOptionsStructNONE                        DataTypeOptionsStruct = 0
	DataTypeOptionsStructUnspecifiedParametersStruct DataTypeOptionsStruct = 1
	DataTypeOptionsStructCommonParametersStruct      DataTypeOptionsStruct = 2
	DataTypeOptionsStructDecimalParametersStruct     DataTypeOptionsStruct = 3
	DataTypeOptionsStructDateParametersStruct        DataTypeOptionsStruct = 4
	DataTypeOptionsStructTimeParametersStruct        DataTypeOptionsStruct = 5
	DataTypeOptionsStructTimestampParametersStruct   DataTypeOptionsStruct = 6
)

var EnumNamesDataTypeOptionsStruct = map[DataTypeOptionsStruct]string{
	DataTypeOptionsStructNONE:                        "NONE",
	DataTypeOptionsStructUnspecifiedParametersStruct: "UnspecifiedParametersStruct",
	DataTypeOptionsStructCommonParametersStruct:      "CommonParametersStruct",
	DataTypeOptionsStructDecimalParametersStruct:     "DecimalParametersStruct",
	DataTypeOptionsStructDateParametersStruct:        "DateParametersStruct",
	DataTypeOptionsStructTimeParametersStruct:        "TimeParametersStruct",
	DataTypeOptionsStructTimestampParametersStruct:   "TimestampParametersStruct",
}

var EnumValuesDataTypeOptionsStruct = map[string]DataTypeOptionsStruct{
	"NONE":                        DataTypeOptionsStructNONE,
	"UnspecifiedParametersStruct": DataTypeOptionsStructUnspecifiedParametersStruct,
	"CommonParametersStruct":      DataTypeOptionsStructCommonParametersStruct,
	"DecimalParametersStruct":     DataTypeOptionsStructDecimalParametersStruct,
	"DateParametersStruct":        DataTypeOptionsStructDateParametersStruct,
	"TimeParametersStruct":        DataTypeOptionsStructTimeParametersStruct,
	"TimestampParametersStruct":   DataTypeOptionsStructTimestampParametersStruct,
}

func (v DataTypeOptionsStruct) String() string {
	if s, ok := EnumNamesDataTypeOptionsStruct[v]; ok {
		return s
	}
	return "DataTypeOptionsStruct(" + strconv.FormatInt(int64(v), 10) + ")"
}
