// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Data type options union.
type DataTypeOptions byte

const (
	DataTypeOptionsNONE          DataTypeOptions = 0
	DataTypeOptionsCommonOpts    DataTypeOptions = 1
	DataTypeOptionsDecimalOpts   DataTypeOptions = 2
	DataTypeOptionsDateOpts      DataTypeOptions = 3
	DataTypeOptionsTimeOpts      DataTypeOptions = 4
	DataTypeOptionsTimestampOpts DataTypeOptions = 5
)

var EnumNamesDataTypeOptions = map[DataTypeOptions]string{
	DataTypeOptionsNONE:          "NONE",
	DataTypeOptionsCommonOpts:    "CommonOpts",
	DataTypeOptionsDecimalOpts:   "DecimalOpts",
	DataTypeOptionsDateOpts:      "DateOpts",
	DataTypeOptionsTimeOpts:      "TimeOpts",
	DataTypeOptionsTimestampOpts: "TimestampOpts",
}

var EnumValuesDataTypeOptions = map[string]DataTypeOptions{
	"NONE":          DataTypeOptionsNONE,
	"CommonOpts":    DataTypeOptionsCommonOpts,
	"DecimalOpts":   DataTypeOptionsDecimalOpts,
	"DateOpts":      DataTypeOptionsDateOpts,
	"TimeOpts":      DataTypeOptionsTimeOpts,
	"TimestampOpts": DataTypeOptionsTimestampOpts,
}

func (v DataTypeOptions) String() string {
	if s, ok := EnumNamesDataTypeOptions[v]; ok {
		return s
	}
	return "DataTypeOptions(" + strconv.FormatInt(int64(v), 10) + ")"
}
