// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"

	enum "enum"
)

/// Date data type options structure.
type DateOpts struct {
	_tab flatbuffers.Table
}

func GetRootAsDateOpts(buf []byte, offset flatbuffers.UOffsetT) *DateOpts {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DateOpts{}
	x.Init(buf, n+offset)
	return x
}

func FinishDateOptsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDateOpts(buf []byte, offset flatbuffers.UOffsetT) *DateOpts {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DateOpts{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDateOptsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DateOpts) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DateOpts) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DateOpts) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DateOpts) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *DateOpts) Unit() enum.DateUnit {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return enum.DateUnit(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DateOpts) MutateUnit(n enum.DateUnit) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func DateOptsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DateOptsAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func DateOptsAddUnit(builder *flatbuffers.Builder, unit enum.DateUnit) {
	builder.PrependInt8Slot(1, int8(unit), 0)
}
func DateOptsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
