// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Options to connect to the Elasticsearch.
type ElasticsearchOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsElasticsearchOptions(buf []byte, offset flatbuffers.UOffsetT) *ElasticsearchOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ElasticsearchOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishElasticsearchOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsElasticsearchOptions(buf []byte, offset flatbuffers.UOffsetT) *ElasticsearchOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ElasticsearchOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedElasticsearchOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ElasticsearchOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ElasticsearchOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ElasticsearchOptions) Host() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchOptions) Port() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ElasticsearchOptions) MutatePort(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *ElasticsearchOptions) User() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchOptions) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchOptions) Ssl() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ElasticsearchOptions) MutateSsl(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ElasticsearchOptions) Region() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchOptions) AccessKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchOptions) SecretKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ElasticsearchOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func ElasticsearchOptionsAddHost(builder *flatbuffers.Builder, host flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(host), 0)
}
func ElasticsearchOptionsAddPort(builder *flatbuffers.Builder, port uint16) {
	builder.PrependUint16Slot(1, port, 0)
}
func ElasticsearchOptionsAddUser(builder *flatbuffers.Builder, user flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(user), 0)
}
func ElasticsearchOptionsAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(password), 0)
}
func ElasticsearchOptionsAddSsl(builder *flatbuffers.Builder, ssl bool) {
	builder.PrependBoolSlot(4, ssl, false)
}
func ElasticsearchOptionsAddRegion(builder *flatbuffers.Builder, region flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(region), 0)
}
func ElasticsearchOptionsAddAccessKey(builder *flatbuffers.Builder, accessKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(accessKey), 0)
}
func ElasticsearchOptionsAddSecretKey(builder *flatbuffers.Builder, secretKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(secretKey), 0)
}
func ElasticsearchOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
