// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Parameters to connect to the Elasticsearch.
type ElasticsearchParametersStruct struct {
	_tab flatbuffers.Table
}

func GetRootAsElasticsearchParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *ElasticsearchParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ElasticsearchParametersStruct{}
	x.Init(buf, n+offset)
	return x
}

func FinishElasticsearchParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsElasticsearchParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *ElasticsearchParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ElasticsearchParametersStruct{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedElasticsearchParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ElasticsearchParametersStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ElasticsearchParametersStruct) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ElasticsearchParametersStruct) Host() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchParametersStruct) Port() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ElasticsearchParametersStruct) MutatePort(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *ElasticsearchParametersStruct) User() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchParametersStruct) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchParametersStruct) Ssl() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ElasticsearchParametersStruct) MutateSsl(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ElasticsearchParametersStruct) Region() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchParametersStruct) AccessKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ElasticsearchParametersStruct) SecretKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ElasticsearchParametersStructStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func ElasticsearchParametersStructAddHost(builder *flatbuffers.Builder, host flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(host), 0)
}
func ElasticsearchParametersStructAddPort(builder *flatbuffers.Builder, port uint16) {
	builder.PrependUint16Slot(1, port, 0)
}
func ElasticsearchParametersStructAddUser(builder *flatbuffers.Builder, user flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(user), 0)
}
func ElasticsearchParametersStructAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(password), 0)
}
func ElasticsearchParametersStructAddSsl(builder *flatbuffers.Builder, ssl bool) {
	builder.PrependBoolSlot(4, ssl, false)
}
func ElasticsearchParametersStructAddRegion(builder *flatbuffers.Builder, region flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(region), 0)
}
func ElasticsearchParametersStructAddAccessKey(builder *flatbuffers.Builder, accessKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(accessKey), 0)
}
func ElasticsearchParametersStructAddSecretKey(builder *flatbuffers.Builder, secretKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(secretKey), 0)
}
func ElasticsearchParametersStructEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
