// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Expression filter parameters.
type ExpressionParametersStruct struct {
	_tab flatbuffers.Table
}

func GetRootAsExpressionParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *ExpressionParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExpressionParametersStruct{}
	x.Init(buf, n+offset)
	return x
}

func FinishExpressionParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExpressionParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *ExpressionParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExpressionParametersStruct{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExpressionParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ExpressionParametersStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExpressionParametersStruct) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ExpressionParametersStruct) Clause() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ExpressionParametersStructStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ExpressionParametersStructAddClause(builder *flatbuffers.Builder, clause flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(clause), 0)
}
func ExpressionParametersStructEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
