// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"

	enum "github.com/HDML-Foundation/HDML-Schemas/lib/go/enum"
)

/// Field type structure.
type FieldTypeStruct struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldTypeStruct(buf []byte, offset flatbuffers.UOffsetT) *FieldTypeStruct {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldTypeStruct{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldTypeStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldTypeStruct(buf []byte, offset flatbuffers.UOffsetT) *FieldTypeStruct {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldTypeStruct{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldTypeStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldTypeStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldTypeStruct) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldTypeStruct) Type() enum.DataTypeEnum {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return enum.DataTypeEnum(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FieldTypeStruct) MutateType(n enum.DataTypeEnum) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *FieldTypeStruct) OptionsType() DataTypeOptionsStruct {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return DataTypeOptionsStruct(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FieldTypeStruct) MutateOptionsType(n DataTypeOptionsStruct) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *FieldTypeStruct) Options(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func FieldTypeStructStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FieldTypeStructAddType(builder *flatbuffers.Builder, type_ enum.DataTypeEnum) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func FieldTypeStructAddOptionsType(builder *flatbuffers.Builder, optionsType DataTypeOptionsStruct) {
	builder.PrependByteSlot(1, byte(optionsType), 0)
}
func FieldTypeStructAddOptions(builder *flatbuffers.Builder, options flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(options), 0)
}
func FieldTypeStructEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
