// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Filter options.
type FilterOptionsStruct byte

const (
	FilterOptionsStructNONE                       FilterOptionsStruct = 0
	FilterOptionsStructExpressionParametersStruct FilterOptionsStruct = 1
	FilterOptionsStructKeysParametersStruct       FilterOptionsStruct = 2
	FilterOptionsStructNamedParametersStruct      FilterOptionsStruct = 3
)

var EnumNamesFilterOptionsStruct = map[FilterOptionsStruct]string{
	FilterOptionsStructNONE:                       "NONE",
	FilterOptionsStructExpressionParametersStruct: "ExpressionParametersStruct",
	FilterOptionsStructKeysParametersStruct:       "KeysParametersStruct",
	FilterOptionsStructNamedParametersStruct:      "NamedParametersStruct",
}

var EnumValuesFilterOptionsStruct = map[string]FilterOptionsStruct{
	"NONE":                       FilterOptionsStructNONE,
	"ExpressionParametersStruct": FilterOptionsStructExpressionParametersStruct,
	"KeysParametersStruct":       FilterOptionsStructKeysParametersStruct,
	"NamedParametersStruct":      FilterOptionsStructNamedParametersStruct,
}

func (v FilterOptionsStruct) String() string {
	if s, ok := EnumNamesFilterOptionsStruct[v]; ok {
		return s
	}
	return "FilterOptionsStruct(" + strconv.FormatInt(int64(v), 10) + ")"
}
