// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"

	enum "github.com/HDML-Foundation/HDML-Schemas/lib/go/enum"
)

/// Single filter structure.
type Filter struct {
	_tab flatbuffers.Table
}

func GetRootAsFilter(buf []byte, offset flatbuffers.UOffsetT) *Filter {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Filter{}
	x.Init(buf, n+offset)
	return x
}

func FinishFilterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFilter(buf []byte, offset flatbuffers.UOffsetT) *Filter {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Filter{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFilterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Filter) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Filter) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Filter) Type() enum.FilterType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return enum.FilterType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Filter) MutateType(n enum.FilterType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *Filter) OptionsType() FilterOptions {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return FilterOptions(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Filter) MutateOptionsType(n FilterOptions) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *Filter) Options(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func FilterStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FilterAddType(builder *flatbuffers.Builder, type_ enum.FilterType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func FilterAddOptionsType(builder *flatbuffers.Builder, optionsType FilterOptions) {
	builder.PrependByteSlot(1, byte(optionsType), 0)
}
func FilterAddOptions(builder *flatbuffers.Builder, options flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(options), 0)
}
func FilterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
