// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Options to connect to the Google Sheets.
type GoogleSheetsOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsGoogleSheetsOptions(buf []byte, offset flatbuffers.UOffsetT) *GoogleSheetsOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GoogleSheetsOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishGoogleSheetsOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGoogleSheetsOptions(buf []byte, offset flatbuffers.UOffsetT) *GoogleSheetsOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GoogleSheetsOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGoogleSheetsOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GoogleSheetsOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GoogleSheetsOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GoogleSheetsOptions) SheetId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GoogleSheetsOptions) CredentialsKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GoogleSheetsOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GoogleSheetsOptionsAddSheetId(builder *flatbuffers.Builder, sheetId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sheetId), 0)
}
func GoogleSheetsOptionsAddCredentialsKey(builder *flatbuffers.Builder, credentialsKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(credentialsKey), 0)
}
func GoogleSheetsOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
