// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Parameters to connect to the Google Sheets.
type GoogleSheetsParametersStruct struct {
	_tab flatbuffers.Table
}

func GetRootAsGoogleSheetsParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *GoogleSheetsParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GoogleSheetsParametersStruct{}
	x.Init(buf, n+offset)
	return x
}

func FinishGoogleSheetsParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGoogleSheetsParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *GoogleSheetsParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GoogleSheetsParametersStruct{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGoogleSheetsParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GoogleSheetsParametersStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GoogleSheetsParametersStruct) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GoogleSheetsParametersStruct) SheetId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GoogleSheetsParametersStruct) CredentialsKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GoogleSheetsParametersStructStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GoogleSheetsParametersStructAddSheetId(builder *flatbuffers.Builder, sheetId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sheetId), 0)
}
func GoogleSheetsParametersStructAddCredentialsKey(builder *flatbuffers.Builder, credentialsKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(credentialsKey), 0)
}
func GoogleSheetsParametersStructEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
