// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"

	enum "github.com/HDML-Foundation/HDML-Schemas/lib/go/enum"
)

/// Timestamp data type parameters structure.
type TimestampParametersStruct struct {
	_tab flatbuffers.Table
}

func GetRootAsTimestampParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *TimestampParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimestampParametersStruct{}
	x.Init(buf, n+offset)
	return x
}

func FinishTimestampParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTimestampParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *TimestampParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TimestampParametersStruct{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTimestampParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TimestampParametersStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimestampParametersStruct) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimestampParametersStruct) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TimestampParametersStruct) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *TimestampParametersStruct) Unit() enum.TimeUnitEnum {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return enum.TimeUnitEnum(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TimestampParametersStruct) MutateUnit(n enum.TimeUnitEnum) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *TimestampParametersStruct) Timezone() enum.TimeZoneEnum {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return enum.TimeZoneEnum(rcv._tab.GetInt16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TimestampParametersStruct) MutateTimezone(n enum.TimeZoneEnum) bool {
	return rcv._tab.MutateInt16Slot(8, int16(n))
}

func TimestampParametersStructStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TimestampParametersStructAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func TimestampParametersStructAddUnit(builder *flatbuffers.Builder, unit enum.TimeUnitEnum) {
	builder.PrependInt8Slot(1, int8(unit), 0)
}
func TimestampParametersStructAddTimezone(builder *flatbuffers.Builder, timezone enum.TimeZoneEnum) {
	builder.PrependInt16Slot(2, int16(timezone), 0)
}
func TimestampParametersStructEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
