// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"

	enum "enum"
)

/// Timestamp data type options structure.
type TimestampOpts struct {
	_tab flatbuffers.Table
}

func GetRootAsTimestampOpts(buf []byte, offset flatbuffers.UOffsetT) *TimestampOpts {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimestampOpts{}
	x.Init(buf, n+offset)
	return x
}

func FinishTimestampOptsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTimestampOpts(buf []byte, offset flatbuffers.UOffsetT) *TimestampOpts {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TimestampOpts{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTimestampOptsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TimestampOpts) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimestampOpts) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimestampOpts) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TimestampOpts) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *TimestampOpts) Unit() enum.TimeUnit {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return enum.TimeUnit(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TimestampOpts) MutateUnit(n enum.TimeUnit) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *TimestampOpts) Timezone() enum.TimeZone {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return enum.TimeZone(rcv._tab.GetInt16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TimestampOpts) MutateTimezone(n enum.TimeZone) bool {
	return rcv._tab.MutateInt16Slot(8, int16(n))
}

func TimestampOptsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TimestampOptsAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func TimestampOptsAddUnit(builder *flatbuffers.Builder, unit enum.TimeUnit) {
	builder.PrependInt8Slot(1, int8(unit), 0)
}
func TimestampOptsAddTimezone(builder *flatbuffers.Builder, timezone enum.TimeZone) {
	builder.PrependInt16Slot(2, int16(timezone), 0)
}
func TimestampOptsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
