// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"

	enum "github.com/HDML-Foundation/HDML-Schemas/lib/go/enum"
)

/// Time data type parameters structure.
type TimeParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsTimeParameters(buf []byte, offset flatbuffers.UOffsetT) *TimeParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimeParameters{}
	x.Init(buf, n+offset)
	return x
}

func FinishTimeParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTimeParameters(buf []byte, offset flatbuffers.UOffsetT) *TimeParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TimeParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTimeParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TimeParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimeParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimeParameters) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TimeParameters) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *TimeParameters) Unit() enum.TimeUnit {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return enum.TimeUnit(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TimeParameters) MutateUnit(n enum.TimeUnit) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func TimeParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TimeParametersAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func TimeParametersAddUnit(builder *flatbuffers.Builder, unit enum.TimeUnit) {
	builder.PrependInt8Slot(1, int8(unit), 0)
}
func TimeParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
