// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Unspecified data type parameters structure.
type UnspecifiedParametersStruct struct {
	_tab flatbuffers.Table
}

func GetRootAsUnspecifiedParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *UnspecifiedParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnspecifiedParametersStruct{}
	x.Init(buf, n+offset)
	return x
}

func FinishUnspecifiedParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUnspecifiedParametersStruct(buf []byte, offset flatbuffers.UOffsetT) *UnspecifiedParametersStruct {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnspecifiedParametersStruct{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUnspecifiedParametersStructBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UnspecifiedParametersStruct) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnspecifiedParametersStruct) Table() flatbuffers.Table {
	return rcv._tab
}

func UnspecifiedParametersStructStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UnspecifiedParametersStructEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
