// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Common data type parameters structure.
 */
export class CommonParameters {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CommonParameters {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCommonParameters(bb:flatbuffers.ByteBuffer, obj?:CommonParameters):CommonParameters {
  return (obj || new CommonParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCommonParameters(bb:flatbuffers.ByteBuffer, obj?:CommonParameters):CommonParameters {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CommonParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startCommonParameters(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(0, +nullable, +false);
}

static endCommonParameters(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCommonParameters(builder:flatbuffers.Builder, nullable:boolean):flatbuffers.Offset {
  CommonParameters.startCommonParameters(builder);
  CommonParameters.addNullable(builder, nullable);
  return CommonParameters.endCommonParameters(builder);
}
}
