// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Common data type options structure.
 */
export class CommonOpts {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CommonOpts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCommonOpts(bb:flatbuffers.ByteBuffer, obj?:CommonOpts):CommonOpts {
  return (obj || new CommonOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCommonOpts(bb:flatbuffers.ByteBuffer, obj?:CommonOpts):CommonOpts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CommonOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startCommonOpts(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(0, +nullable, +false);
}

static endCommonOpts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCommonOpts(builder:flatbuffers.Builder, nullable:boolean):flatbuffers.Offset {
  CommonOpts.startCommonOpts(builder);
  CommonOpts.addNullable(builder, nullable);
  return CommonOpts.endCommonOpts(builder);
}
}
