// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BigQueryOptions } from '../document/big-query-options.js';
import { ElasticsearchOptions } from '../document/elasticsearch-options.js';
import { GoogleSheetsOptions } from '../document/google-sheets-options.js';
import { JDBCOptions } from '../document/jdbcoptions.js';
import { MongoDBOptions } from '../document/mongo-dboptions.js';


/**
 * Union type to describe DB connection options.
 */
export enum ConnectionOptionsUnion {
  NONE = 0,
  JDBCOptions = 1,
  BigQueryOptions = 2,
  GoogleSheetsOptions = 3,
  ElasticsearchOptions = 4,
  MongoDBOptions = 5
}

export function unionToConnectionOptionsUnion(
  type: ConnectionOptionsUnion,
  accessor: (obj:BigQueryOptions|ElasticsearchOptions|GoogleSheetsOptions|JDBCOptions|MongoDBOptions) => BigQueryOptions|ElasticsearchOptions|GoogleSheetsOptions|JDBCOptions|MongoDBOptions|null
): BigQueryOptions|ElasticsearchOptions|GoogleSheetsOptions|JDBCOptions|MongoDBOptions|null {
  switch(ConnectionOptionsUnion[type]) {
    case 'NONE': return null; 
    case 'JDBCOptions': return accessor(new JDBCOptions())! as JDBCOptions;
    case 'BigQueryOptions': return accessor(new BigQueryOptions())! as BigQueryOptions;
    case 'GoogleSheetsOptions': return accessor(new GoogleSheetsOptions())! as GoogleSheetsOptions;
    case 'ElasticsearchOptions': return accessor(new ElasticsearchOptions())! as ElasticsearchOptions;
    case 'MongoDBOptions': return accessor(new MongoDBOptions())! as MongoDBOptions;
    default: return null;
  }
}

export function unionListToConnectionOptionsUnion(
  type: ConnectionOptionsUnion, 
  accessor: (index: number, obj:BigQueryOptions|ElasticsearchOptions|GoogleSheetsOptions|JDBCOptions|MongoDBOptions) => BigQueryOptions|ElasticsearchOptions|GoogleSheetsOptions|JDBCOptions|MongoDBOptions|null, 
  index: number
): BigQueryOptions|ElasticsearchOptions|GoogleSheetsOptions|JDBCOptions|MongoDBOptions|null {
  switch(ConnectionOptionsUnion[type]) {
    case 'NONE': return null; 
    case 'JDBCOptions': return accessor(index, new JDBCOptions())! as JDBCOptions;
    case 'BigQueryOptions': return accessor(index, new BigQueryOptions())! as BigQueryOptions;
    case 'GoogleSheetsOptions': return accessor(index, new GoogleSheetsOptions())! as GoogleSheetsOptions;
    case 'ElasticsearchOptions': return accessor(index, new ElasticsearchOptions())! as ElasticsearchOptions;
    case 'MongoDBOptions': return accessor(index, new MongoDBOptions())! as MongoDBOptions;
    default: return null;
  }
}
