// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ConnectionOptionsUnion, unionToConnectionOptionsUnion, unionListToConnectionOptionsUnion } from '../document/connection-options-union.js';
import { ConnectionTypes } from '../enum/connection-types.js';


/**
 * Database connection options structure.
 */
export class ConnectionOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConnectionOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConnectionOptions(bb:flatbuffers.ByteBuffer, obj?:ConnectionOptions):ConnectionOptions {
  return (obj || new ConnectionOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConnectionOptions(bb:flatbuffers.ByteBuffer, obj?:ConnectionOptions):ConnectionOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConnectionOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():ConnectionTypes {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ConnectionTypes.Postgres;
}

optionsType():ConnectionOptionsUnion {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ConnectionOptionsUnion.NONE;
}

options<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startConnectionOptions(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addType(builder:flatbuffers.Builder, type:ConnectionTypes) {
  builder.addFieldInt8(0, type, ConnectionTypes.Postgres);
}

static addOptionsType(builder:flatbuffers.Builder, optionsType:ConnectionOptionsUnion) {
  builder.addFieldInt8(1, optionsType, ConnectionOptionsUnion.NONE);
}

static addOptions(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, optionsOffset, 0);
}

static endConnectionOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConnectionOptions(builder:flatbuffers.Builder, type:ConnectionTypes, optionsType:ConnectionOptionsUnion, optionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConnectionOptions.startConnectionOptions(builder);
  ConnectionOptions.addType(builder, type);
  ConnectionOptions.addOptionsType(builder, optionsType);
  ConnectionOptions.addOptions(builder, optionsOffset);
  return ConnectionOptions.endConnectionOptions(builder);
}
}
