// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CommonOpts } from '../document/common-opts.js';
import { DateOpts } from '../document/date-opts.js';
import { DecimalOpts } from '../document/decimal-opts.js';
import { TimeOpts } from '../document/time-opts.js';
import { TimestampOpts } from '../document/timestamp-opts.js';


/**
 * Data type options union.
 */
export enum DataTypeOptions {
  NONE = 0,
  CommonOpts = 1,
  DecimalOpts = 2,
  DateOpts = 3,
  TimeOpts = 4,
  TimestampOpts = 5
}

export function unionToDataTypeOptions(
  type: DataTypeOptions,
  accessor: (obj:CommonOpts|DateOpts|DecimalOpts|TimeOpts|TimestampOpts) => CommonOpts|DateOpts|DecimalOpts|TimeOpts|TimestampOpts|null
): CommonOpts|DateOpts|DecimalOpts|TimeOpts|TimestampOpts|null {
  switch(DataTypeOptions[type]) {
    case 'NONE': return null; 
    case 'CommonOpts': return accessor(new CommonOpts())! as CommonOpts;
    case 'DecimalOpts': return accessor(new DecimalOpts())! as DecimalOpts;
    case 'DateOpts': return accessor(new DateOpts())! as DateOpts;
    case 'TimeOpts': return accessor(new TimeOpts())! as TimeOpts;
    case 'TimestampOpts': return accessor(new TimestampOpts())! as TimestampOpts;
    default: return null;
  }
}

export function unionListToDataTypeOptions(
  type: DataTypeOptions, 
  accessor: (index: number, obj:CommonOpts|DateOpts|DecimalOpts|TimeOpts|TimestampOpts) => CommonOpts|DateOpts|DecimalOpts|TimeOpts|TimestampOpts|null, 
  index: number
): CommonOpts|DateOpts|DecimalOpts|TimeOpts|TimestampOpts|null {
  switch(DataTypeOptions[type]) {
    case 'NONE': return null; 
    case 'CommonOpts': return accessor(index, new CommonOpts())! as CommonOpts;
    case 'DecimalOpts': return accessor(index, new DecimalOpts())! as DecimalOpts;
    case 'DateOpts': return accessor(index, new DateOpts())! as DateOpts;
    case 'TimeOpts': return accessor(index, new TimeOpts())! as TimeOpts;
    case 'TimestampOpts': return accessor(index, new TimestampOpts())! as TimestampOpts;
    default: return null;
  }
}
