// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DateUnit } from '../enum/date-unit.js';


/**
 * Date data type options structure.
 */
export class DateOpts {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DateOpts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDateOpts(bb:flatbuffers.ByteBuffer, obj?:DateOpts):DateOpts {
  return (obj || new DateOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDateOpts(bb:flatbuffers.ByteBuffer, obj?:DateOpts):DateOpts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DateOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

unit():DateUnit {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : DateUnit.second;
}

static startDateOpts(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(0, +nullable, +false);
}

static addUnit(builder:flatbuffers.Builder, unit:DateUnit) {
  builder.addFieldInt8(1, unit, DateUnit.second);
}

static endDateOpts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDateOpts(builder:flatbuffers.Builder, nullable:boolean, unit:DateUnit):flatbuffers.Offset {
  DateOpts.startDateOpts(builder);
  DateOpts.addNullable(builder, nullable);
  DateOpts.addUnit(builder, unit);
  return DateOpts.endDateOpts(builder);
}
}
