// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DecBitWidth } from '../enum/dec-bit-width.js';


/**
 * Decimal data type options structure.
 */
export class DecimalOpts {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DecimalOpts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDecimalOpts(bb:flatbuffers.ByteBuffer, obj?:DecimalOpts):DecimalOpts {
  return (obj || new DecimalOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDecimalOpts(bb:flatbuffers.ByteBuffer, obj?:DecimalOpts):DecimalOpts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DecimalOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

scale():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

precision():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

bitWidth():DecBitWidth {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : DecBitWidth._128;
}

static startDecimalOpts(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(0, +nullable, +false);
}

static addScale(builder:flatbuffers.Builder, scale:number) {
  builder.addFieldInt16(1, scale, 0);
}

static addPrecision(builder:flatbuffers.Builder, precision:number) {
  builder.addFieldInt16(2, precision, 0);
}

static addBitWidth(builder:flatbuffers.Builder, bitWidth:DecBitWidth) {
  builder.addFieldInt8(3, bitWidth, DecBitWidth._128);
}

static endDecimalOpts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDecimalOpts(builder:flatbuffers.Builder, nullable:boolean, scale:number, precision:number, bitWidth:DecBitWidth):flatbuffers.Offset {
  DecimalOpts.startDecimalOpts(builder);
  DecimalOpts.addNullable(builder, nullable);
  DecimalOpts.addScale(builder, scale);
  DecimalOpts.addPrecision(builder, precision);
  DecimalOpts.addBitWidth(builder, bitWidth);
  return DecimalOpts.endDecimalOpts(builder);
}
}
