// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Expression filter parameters.
 */
export class ExpressionParameters {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ExpressionParameters {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsExpressionParameters(bb:flatbuffers.ByteBuffer, obj?:ExpressionParameters):ExpressionParameters {
  return (obj || new ExpressionParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsExpressionParameters(bb:flatbuffers.ByteBuffer, obj?:ExpressionParameters):ExpressionParameters {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ExpressionParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clause():string|null
clause(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clause(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startExpressionParameters(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addClause(builder:flatbuffers.Builder, clauseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, clauseOffset, 0);
}

static endExpressionParameters(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createExpressionParameters(builder:flatbuffers.Builder, clauseOffset:flatbuffers.Offset):flatbuffers.Offset {
  ExpressionParameters.startExpressionParameters(builder);
  ExpressionParameters.addClause(builder, clauseOffset);
  return ExpressionParameters.endExpressionParameters(builder);
}
}
