// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Options to connect to the Google Sheets.
 */
export class GoogleSheetsOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GoogleSheetsOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGoogleSheetsOptions(bb:flatbuffers.ByteBuffer, obj?:GoogleSheetsOptions):GoogleSheetsOptions {
  return (obj || new GoogleSheetsOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGoogleSheetsOptions(bb:flatbuffers.ByteBuffer, obj?:GoogleSheetsOptions):GoogleSheetsOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GoogleSheetsOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sheetId():string|null
sheetId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sheetId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

credentialsKey():string|null
credentialsKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
credentialsKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGoogleSheetsOptions(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSheetId(builder:flatbuffers.Builder, sheetIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sheetIdOffset, 0);
}

static addCredentialsKey(builder:flatbuffers.Builder, credentialsKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, credentialsKeyOffset, 0);
}

static endGoogleSheetsOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // sheet_id
  builder.requiredField(offset, 6) // credentials_key
  return offset;
}

static createGoogleSheetsOptions(builder:flatbuffers.Builder, sheetIdOffset:flatbuffers.Offset, credentialsKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  GoogleSheetsOptions.startGoogleSheetsOptions(builder);
  GoogleSheetsOptions.addSheetId(builder, sheetIdOffset);
  GoogleSheetsOptions.addCredentialsKey(builder, credentialsKeyOffset);
  return GoogleSheetsOptions.endGoogleSheetsOptions(builder);
}
}
