// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TimeUnit } from '../enum/time-unit.js';


/**
 * Time data type options structure.
 */
export class TimeOpts {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TimeOpts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTimeOpts(bb:flatbuffers.ByteBuffer, obj?:TimeOpts):TimeOpts {
  return (obj || new TimeOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTimeOpts(bb:flatbuffers.ByteBuffer, obj?:TimeOpts):TimeOpts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TimeOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

unit():TimeUnit {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TimeUnit.second;
}

static startTimeOpts(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(0, +nullable, +false);
}

static addUnit(builder:flatbuffers.Builder, unit:TimeUnit) {
  builder.addFieldInt8(1, unit, TimeUnit.second);
}

static endTimeOpts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTimeOpts(builder:flatbuffers.Builder, nullable:boolean, unit:TimeUnit):flatbuffers.Offset {
  TimeOpts.startTimeOpts(builder);
  TimeOpts.addNullable(builder, nullable);
  TimeOpts.addUnit(builder, unit);
  return TimeOpts.endTimeOpts(builder);
}
}
