// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TimeUnit } from '../enum/time-unit.js';
import { TimeZone } from '../enum/time-zone.js';


/**
 * Timestamp data type options structure.
 */
export class TimestampOpts {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TimestampOpts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTimestampOpts(bb:flatbuffers.ByteBuffer, obj?:TimestampOpts):TimestampOpts {
  return (obj || new TimestampOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTimestampOpts(bb:flatbuffers.ByteBuffer, obj?:TimestampOpts):TimestampOpts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TimestampOpts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

unit():TimeUnit {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TimeUnit.second;
}

timezone():TimeZone {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : TimeZone.GMT_00;
}

static startTimestampOpts(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(0, +nullable, +false);
}

static addUnit(builder:flatbuffers.Builder, unit:TimeUnit) {
  builder.addFieldInt8(1, unit, TimeUnit.second);
}

static addTimezone(builder:flatbuffers.Builder, timezone:TimeZone) {
  builder.addFieldInt16(2, timezone, TimeZone.GMT_00);
}

static endTimestampOpts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTimestampOpts(builder:flatbuffers.Builder, nullable:boolean, unit:TimeUnit, timezone:TimeZone):flatbuffers.Offset {
  TimestampOpts.startTimestampOpts(builder);
  TimestampOpts.addNullable(builder, nullable);
  TimestampOpts.addUnit(builder, unit);
  TimestampOpts.addTimezone(builder, timezone);
  return TimestampOpts.endTimestampOpts(builder);
}
}
