// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Parameters to connect to the BigQuery.
type BigQueryParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsBigQueryParameters(buf []byte, offset flatbuffers.UOffsetT) *BigQueryParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BigQueryParameters{}
	x.Init(buf, n+offset)
	return x
}

func FinishBigQueryParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBigQueryParameters(buf []byte, offset flatbuffers.UOffsetT) *BigQueryParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BigQueryParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBigQueryParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BigQueryParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BigQueryParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BigQueryParameters) ProjectId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BigQueryParameters) CredentialsKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BigQueryParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BigQueryParametersAddProjectId(builder *flatbuffers.Builder, projectId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(projectId), 0)
}
func BigQueryParametersAddCredentialsKey(builder *flatbuffers.Builder, credentialsKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(credentialsKey), 0)
}
func BigQueryParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
