// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Common data type parameters structure.
type CommonParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsCommonParameters(buf []byte, offset flatbuffers.UOffsetT) *CommonParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommonParameters{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommonParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommonParameters(buf []byte, offset flatbuffers.UOffsetT) *CommonParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommonParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommonParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CommonParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommonParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommonParameters) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CommonParameters) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func CommonParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CommonParametersAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func CommonParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
