// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"

	enum "enum"
)

/// Date data type parameters structure.
type DateParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsDateParameters(buf []byte, offset flatbuffers.UOffsetT) *DateParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DateParameters{}
	x.Init(buf, n+offset)
	return x
}

func FinishDateParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDateParameters(buf []byte, offset flatbuffers.UOffsetT) *DateParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DateParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDateParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DateParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DateParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DateParameters) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DateParameters) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *DateParameters) Unit() enum.DateUnit {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return enum.DateUnit(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DateParameters) MutateUnit(n enum.DateUnit) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func DateParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DateParametersAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(0, nullable, false)
}
func DateParametersAddUnit(builder *flatbuffers.Builder, unit enum.DateUnit) {
	builder.PrependInt8Slot(1, int8(unit), 0)
}
func DateParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
