// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import "strconv"

/// Filter options.
type FilterOptions byte

const (
	FilterOptionsNONE                 FilterOptions = 0
	FilterOptionsExpressionParameters FilterOptions = 1
	FilterOptionsKeysParameters       FilterOptions = 2
	FilterOptionsNamedParameters      FilterOptions = 3
)

var EnumNamesFilterOptions = map[FilterOptions]string{
	FilterOptionsNONE:                 "NONE",
	FilterOptionsExpressionParameters: "ExpressionParameters",
	FilterOptionsKeysParameters:       "KeysParameters",
	FilterOptionsNamedParameters:      "NamedParameters",
}

var EnumValuesFilterOptions = map[string]FilterOptions{
	"NONE":                 FilterOptionsNONE,
	"ExpressionParameters": FilterOptionsExpressionParameters,
	"KeysParameters":       FilterOptionsKeysParameters,
	"NamedParameters":      FilterOptionsNamedParameters,
}

func (v FilterOptions) String() string {
	if s, ok := EnumNamesFilterOptions[v]; ok {
		return s
	}
	return "FilterOptions(" + strconv.FormatInt(int64(v), 10) + ")"
}
