// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Parameters to connect to the Google Sheets.
type GoogleSheetsParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsGoogleSheetsParameters(buf []byte, offset flatbuffers.UOffsetT) *GoogleSheetsParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GoogleSheetsParameters{}
	x.Init(buf, n+offset)
	return x
}

func FinishGoogleSheetsParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGoogleSheetsParameters(buf []byte, offset flatbuffers.UOffsetT) *GoogleSheetsParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GoogleSheetsParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGoogleSheetsParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GoogleSheetsParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GoogleSheetsParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GoogleSheetsParameters) SheetId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GoogleSheetsParameters) CredentialsKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GoogleSheetsParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GoogleSheetsParametersAddSheetId(builder *flatbuffers.Builder, sheetId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sheetId), 0)
}
func GoogleSheetsParametersAddCredentialsKey(builder *flatbuffers.Builder, credentialsKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(credentialsKey), 0)
}
func GoogleSheetsParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
