// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Parameters to connect to one the of the following DB: Postgres,
/// MySQL, MS SQL, MariaDB, Oracle, ClickHouse, Druid, Ignite,
/// Redshift.
type JDBCParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsJDBCParameters(buf []byte, offset flatbuffers.UOffsetT) *JDBCParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JDBCParameters{}
	x.Init(buf, n+offset)
	return x
}

func FinishJDBCParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJDBCParameters(buf []byte, offset flatbuffers.UOffsetT) *JDBCParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JDBCParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJDBCParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JDBCParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JDBCParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JDBCParameters) Host() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JDBCParameters) User() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JDBCParameters) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JDBCParameters) Ssl() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *JDBCParameters) MutateSsl(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func JDBCParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func JDBCParametersAddHost(builder *flatbuffers.Builder, host flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(host), 0)
}
func JDBCParametersAddUser(builder *flatbuffers.Builder, user flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(user), 0)
}
func JDBCParametersAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(password), 0)
}
func JDBCParametersAddSsl(builder *flatbuffers.Builder, ssl bool) {
	builder.PrependBoolSlot(3, ssl, false)
}
func JDBCParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
