// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Data types enum.
type DataType int8

const (
	DataTypeInt8      DataType = 0
	DataTypeInt16     DataType = 1
	DataTypeInt32     DataType = 2
	DataTypeInt64     DataType = 3
	DataTypeFloat32   DataType = 4
	DataTypeFloat64   DataType = 5
	DataTypeDecimal   DataType = 6
	DataTypeDate      DataType = 7
	DataTypeTime      DataType = 8
	DataTypeTimestamp DataType = 9
	DataTypeBinary    DataType = 10
	DataTypeUtf8      DataType = 11
)

var EnumNamesDataType = map[DataType]string{
	DataTypeInt8:      "Int8",
	DataTypeInt16:     "Int16",
	DataTypeInt32:     "Int32",
	DataTypeInt64:     "Int64",
	DataTypeFloat32:   "Float32",
	DataTypeFloat64:   "Float64",
	DataTypeDecimal:   "Decimal",
	DataTypeDate:      "Date",
	DataTypeTime:      "Time",
	DataTypeTimestamp: "Timestamp",
	DataTypeBinary:    "Binary",
	DataTypeUtf8:      "Utf8",
}

var EnumValuesDataType = map[string]DataType{
	"Int8":      DataTypeInt8,
	"Int16":     DataTypeInt16,
	"Int32":     DataTypeInt32,
	"Int64":     DataTypeInt64,
	"Float32":   DataTypeFloat32,
	"Float64":   DataTypeFloat64,
	"Decimal":   DataTypeDecimal,
	"Date":      DataTypeDate,
	"Time":      DataTypeTime,
	"Timestamp": DataTypeTimestamp,
	"Binary":    DataTypeBinary,
	"Utf8":      DataTypeUtf8,
}

func (v DataType) String() string {
	if s, ok := EnumNamesDataType[v]; ok {
		return s
	}
	return "DataType(" + strconv.FormatInt(int64(v), 10) + ")"
}
