// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Date units enum.
type DateUnit int8

const (
	DateUnitSecond      DateUnit = 0
	DateUnitMillisecond DateUnit = 1
)

var EnumNamesDateUnit = map[DateUnit]string{
	DateUnitSecond:      "Second",
	DateUnitMillisecond: "Millisecond",
}

var EnumValuesDateUnit = map[string]DateUnit{
	"Second":      DateUnitSecond,
	"Millisecond": DateUnitMillisecond,
}

func (v DateUnit) String() string {
	if s, ok := EnumNamesDateUnit[v]; ok {
		return s
	}
	return "DateUnit(" + strconv.FormatInt(int64(v), 10) + ")"
}
