// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Decimal data type bit width enum.
type DecimalBitWidth int8

const (
	DecimalBitWidth_128 DecimalBitWidth = 0
	DecimalBitWidth_256 DecimalBitWidth = 1
)

var EnumNamesDecimalBitWidth = map[DecimalBitWidth]string{
	DecimalBitWidth_128: "_128",
	DecimalBitWidth_256: "_256",
}

var EnumValuesDecimalBitWidth = map[string]DecimalBitWidth{
	"_128": DecimalBitWidth_128,
	"_256": DecimalBitWidth_256,
}

func (v DecimalBitWidth) String() string {
	if s, ok := EnumNamesDecimalBitWidth[v]; ok {
		return s
	}
	return "DecimalBitWidth(" + strconv.FormatInt(int64(v), 10) + ")"
}
