// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Join types enum.
type JoinType int8

const (
	JoinTypeCross      JoinType = 0
	JoinTypeInner      JoinType = 1
	JoinTypeFull       JoinType = 2
	JoinTypeLeft       JoinType = 3
	JoinTypeRight      JoinType = 4
	JoinTypeFullOuter  JoinType = 5
	JoinTypeLeftOuter  JoinType = 6
	JoinTypeRightOuter JoinType = 7
)

var EnumNamesJoinType = map[JoinType]string{
	JoinTypeCross:      "Cross",
	JoinTypeInner:      "Inner",
	JoinTypeFull:       "Full",
	JoinTypeLeft:       "Left",
	JoinTypeRight:      "Right",
	JoinTypeFullOuter:  "FullOuter",
	JoinTypeLeftOuter:  "LeftOuter",
	JoinTypeRightOuter: "RightOuter",
}

var EnumValuesJoinType = map[string]JoinType{
	"Cross":      JoinTypeCross,
	"Inner":      JoinTypeInner,
	"Full":       JoinTypeFull,
	"Left":       JoinTypeLeft,
	"Right":      JoinTypeRight,
	"FullOuter":  JoinTypeFullOuter,
	"LeftOuter":  JoinTypeLeftOuter,
	"RightOuter": JoinTypeRightOuter,
}

func (v JoinType) String() string {
	if s, ok := EnumNamesJoinType[v]; ok {
		return s
	}
	return "JoinType(" + strconv.FormatInt(int64(v), 10) + ")"
}
