// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Ordering types enum.
type OrderType int8

const (
	OrderTypeNone       OrderType = 0
	OrderTypeAscending  OrderType = 1
	OrderTypeDescending OrderType = 2
)

var EnumNamesOrderType = map[OrderType]string{
	OrderTypeNone:       "None",
	OrderTypeAscending:  "Ascending",
	OrderTypeDescending: "Descending",
}

var EnumValuesOrderType = map[string]OrderType{
	"None":       OrderTypeNone,
	"Ascending":  OrderTypeAscending,
	"Descending": OrderTypeDescending,
}

func (v OrderType) String() string {
	if s, ok := EnumNamesOrderType[v]; ok {
		return s
	}
	return "OrderType(" + strconv.FormatInt(int64(v), 10) + ")"
}
