// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enum

import "strconv"

/// Table types enum.
type TableType int8

const (
	TableTypeTable TableType = 0
	TableTypeQuery TableType = 1
)

var EnumNamesTableType = map[TableType]string{
	TableTypeTable: "Table",
	TableTypeQuery: "Query",
}

var EnumValuesTableType = map[string]TableType{
	"Table": TableTypeTable,
	"Query": TableTypeQuery,
}

func (v TableType) String() string {
	if s, ok := EnumNamesTableType[v]; ok {
		return s
	}
	return "TableType(" + strconv.FormatInt(int64(v), 10) + ")"
}
