#!/bin/bash

# Repository MUST be added to the trusted repos by clicking on "Manage
# unsafe repositories" button and picking it up from the dropdown (for
# VSCode).

git config --global --add safe.directory /workspaces/HDML-Schemas
git config core.sshCommand "$(which ssh) -i /home/.ssh/hdml.github"
cp /workspaces/HDML-Schemas/scripts/pre-commit /workspaces/HDML-Schemas/.git/hooks
chmod +x /workspaces/HDML-Schemas/.git/hooks/pre-commit