#!/bin/bash

# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

rm -rf ./lib/ts/src/document && \
rm -rf ./lib/ts/src/enum && \
rm -rf ./lib/go/document && \
rm -rf ./lib/go/enum && \
flatc --ts --ts-omit-entrypoint -o ./lib/ts/src -I ./src ./src/*.fbs && \
flatc --go --go-module-name github.com/HDML-Foundation/HDML-Schemas/lib/go -o ./lib/go -I ./src ./src/*.fbs && \
git add .