// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TimeUnit } from '../enum/time-unit.js';
import { TimeZone } from '../enum/time-zone.js';


/**
 * Timestamp data type parameters structure.
 */
export class TimestampParameters {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TimestampParameters {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTimestampParameters(bb:flatbuffers.ByteBuffer, obj?:TimestampParameters):TimestampParameters {
  return (obj || new TimestampParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTimestampParameters(bb:flatbuffers.ByteBuffer, obj?:TimestampParameters):TimestampParameters {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TimestampParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

unit():TimeUnit {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TimeUnit.Second;
}

timezone():TimeZone {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : TimeZone.UTC;
}

static startTimestampParameters(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(0, +nullable, +false);
}

static addUnit(builder:flatbuffers.Builder, unit:TimeUnit) {
  builder.addFieldInt8(1, unit, TimeUnit.Second);
}

static addTimezone(builder:flatbuffers.Builder, timezone:TimeZone) {
  builder.addFieldInt16(2, timezone, TimeZone.UTC);
}

static endTimestampParameters(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTimestampParameters(builder:flatbuffers.Builder, nullable:boolean, unit:TimeUnit, timezone:TimeZone):flatbuffers.Offset {
  TimestampParameters.startTimestampParameters(builder);
  TimestampParameters.addNullable(builder, nullable);
  TimestampParameters.addUnit(builder, unit);
  TimestampParameters.addTimezone(builder, timezone);
  return TimestampParameters.endTimestampParameters(builder);
}
}
