# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Main Branch

on:
  push:
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/main.yml'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'src/**'
      - 'lib/ts/src/**'
      - 'lib/ts/tsconfig/**'
      - 'lib/ts/.eslintrc.js'
      - 'lib/ts/.jestrc.js'
      - 'lib/ts/package-lock.json'
      - 'lib/ts/package.json'
      - 'README.md'
    branches:
      - 'main'
  pull_request:
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/main.yml'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'src/**'
      - 'lib/ts/src/**'
      - 'lib/ts/tsconfig/**'
      - 'lib/ts/.eslintrc.js'
      - 'lib/ts/.jestrc.js'
      - 'lib/ts/package-lock.json'
      - 'lib/ts/package.json'
      - 'README.md'

jobs:
  build_devcontainer:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v4
    # if
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          devcontainer:
            - '.devcontainer/Dockerfile'
    # then
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: steps.filter.outputs.devcontainer == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.HDML_FOUNDATION_DOCKER_NAME }}
        password: ${{ secrets.HDML_FOUNDATION_DOCKER }}
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: hdio/hdml-schemas-dev
        cacheFrom: hdio/hdml-schemas-dev
        push: always
    # else
    - name: No Changes Warning
      if: steps.filter.outputs.workflows != 'true'
      run: echo "DevContainer was not changed"

  build_ts:
    runs-on: ubuntu-latest
    needs: build_devcontainer
    timeout-minutes: 5
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Build TS library
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: hdio/hdml-schemas-dev
          runCmd: ls -la && cd lib/ts && npm ci && npm run build
          push: never