# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Main Branch

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'src/**'
      - 'lib/ts/src/**'
      - 'lib/ts/tsconfig/**'
      - 'lib/ts/.eslintrc.js'
      - 'lib/ts/.jestrc.js'
      - 'lib/ts/package-lock.json'
      - 'lib/ts/package.json'
      - 'README.md'
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'src/**'
      - 'lib/ts/src/**'
      - 'lib/ts/tsconfig/**'
      - 'lib/ts/.eslintrc.js'
      - 'lib/ts/.jestrc.js'
      - 'lib/ts/package-lock.json'
      - 'lib/ts/package.json'
      - 'README.md'

jobs:
  build_ts:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Install NPM dependencies
      #   run: ls -la && cd lib/ts && npm ci
      - name: Build TS library
      #   run: ls -la && cd lib/ts && npm run build
        uses: devcontainers/ci@v0.3
        with:
          runCmd: ls -la && cd lib/ts && npm ci && npm run build